-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity image_filter is
port (
    INPUT_STREAM_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    INPUT_STREAM_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    INPUT_STREAM_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    INPUT_STREAM_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    INPUT_STREAM_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    INPUT_STREAM_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    INPUT_STREAM_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    OUTPUT_STREAM_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    OUTPUT_STREAM_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    OUTPUT_STREAM_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    OUTPUT_STREAM_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    OUTPUT_STREAM_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    OUTPUT_STREAM_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
    OUTPUT_STREAM_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    INPUT_STREAM_TVALID : IN STD_LOGIC;
    INPUT_STREAM_TREADY : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    OUTPUT_STREAM_TVALID : OUT STD_LOGIC;
    OUTPUT_STREAM_TREADY : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of image_filter is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "image_filter,hls_ip_2018_3,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=6.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=5.250000,HLS_SYN_LAT=151190,HLS_SYN_TPT=151188,HLS_SYN_MEM=24,HLS_SYN_DSP=84,HLS_SYN_FF=7124,HLS_SYN_LUT=8787,HLS_VERSION=2018_3}";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal AXIvideo2Mat_U0_ap_start : STD_LOGIC;
    signal AXIvideo2Mat_U0_ap_done : STD_LOGIC;
    signal AXIvideo2Mat_U0_ap_continue : STD_LOGIC;
    signal AXIvideo2Mat_U0_ap_idle : STD_LOGIC;
    signal AXIvideo2Mat_U0_ap_ready : STD_LOGIC;
    signal AXIvideo2Mat_U0_start_out : STD_LOGIC;
    signal AXIvideo2Mat_U0_start_write : STD_LOGIC;
    signal AXIvideo2Mat_U0_INPUT_STREAM_TREADY : STD_LOGIC;
    signal AXIvideo2Mat_U0_img_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal AXIvideo2Mat_U0_img_data_stream_0_V_write : STD_LOGIC;
    signal AXIvideo2Mat_U0_img_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal AXIvideo2Mat_U0_img_data_stream_1_V_write : STD_LOGIC;
    signal AXIvideo2Mat_U0_img_data_stream_2_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal AXIvideo2Mat_U0_img_data_stream_2_V_write : STD_LOGIC;
    signal replicate_by2_U0_ap_start : STD_LOGIC;
    signal replicate_by2_U0_start_full_n : STD_LOGIC;
    signal replicate_by2_U0_ap_done : STD_LOGIC;
    signal replicate_by2_U0_ap_continue : STD_LOGIC;
    signal replicate_by2_U0_ap_idle : STD_LOGIC;
    signal replicate_by2_U0_ap_ready : STD_LOGIC;
    signal replicate_by2_U0_start_out : STD_LOGIC;
    signal replicate_by2_U0_start_write : STD_LOGIC;
    signal replicate_by2_U0_img_in_data_stream_0_V_read : STD_LOGIC;
    signal replicate_by2_U0_img_in_data_stream_1_V_read : STD_LOGIC;
    signal replicate_by2_U0_img_in_data_stream_2_V_read : STD_LOGIC;
    signal replicate_by2_U0_img_out0_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal replicate_by2_U0_img_out0_data_stream_0_V_write : STD_LOGIC;
    signal replicate_by2_U0_img_out0_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal replicate_by2_U0_img_out0_data_stream_1_V_write : STD_LOGIC;
    signal replicate_by2_U0_img_out0_data_stream_2_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal replicate_by2_U0_img_out0_data_stream_2_V_write : STD_LOGIC;
    signal replicate_by2_U0_img_out1_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal replicate_by2_U0_img_out1_data_stream_0_V_write : STD_LOGIC;
    signal replicate_by2_U0_img_out1_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal replicate_by2_U0_img_out1_data_stream_1_V_write : STD_LOGIC;
    signal replicate_by2_U0_img_out1_data_stream_2_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal replicate_by2_U0_img_out1_data_stream_2_V_write : STD_LOGIC;
    signal grad_vertical_Mat_U0_ap_start : STD_LOGIC;
    signal grad_vertical_Mat_U0_ap_done : STD_LOGIC;
    signal grad_vertical_Mat_U0_ap_continue : STD_LOGIC;
    signal grad_vertical_Mat_U0_ap_idle : STD_LOGIC;
    signal grad_vertical_Mat_U0_ap_ready : STD_LOGIC;
    signal grad_vertical_Mat_U0_start_out : STD_LOGIC;
    signal grad_vertical_Mat_U0_start_write : STD_LOGIC;
    signal grad_vertical_Mat_U0_img_in_data_stream_0_V_read : STD_LOGIC;
    signal grad_vertical_Mat_U0_img_in_data_stream_1_V_read : STD_LOGIC;
    signal grad_vertical_Mat_U0_img_in_data_stream_2_V_read : STD_LOGIC;
    signal grad_vertical_Mat_U0_img_out_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grad_vertical_Mat_U0_img_out_data_stream_0_V_write : STD_LOGIC;
    signal grad_vertical_Mat_U0_img_out_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grad_vertical_Mat_U0_img_out_data_stream_1_V_write : STD_LOGIC;
    signal grad_vertical_Mat_U0_img_out_data_stream_2_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grad_vertical_Mat_U0_img_out_data_stream_2_V_write : STD_LOGIC;
    signal grad_horizontal_U0_ap_start : STD_LOGIC;
    signal grad_horizontal_U0_ap_done : STD_LOGIC;
    signal grad_horizontal_U0_ap_continue : STD_LOGIC;
    signal grad_horizontal_U0_ap_idle : STD_LOGIC;
    signal grad_horizontal_U0_ap_ready : STD_LOGIC;
    signal grad_horizontal_U0_img_in_data_stream_0_V_read : STD_LOGIC;
    signal grad_horizontal_U0_img_in_data_stream_1_V_read : STD_LOGIC;
    signal grad_horizontal_U0_img_in_data_stream_2_V_read : STD_LOGIC;
    signal grad_horizontal_U0_img_out_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grad_horizontal_U0_img_out_data_stream_0_V_write : STD_LOGIC;
    signal grad_horizontal_U0_img_out_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grad_horizontal_U0_img_out_data_stream_1_V_write : STD_LOGIC;
    signal grad_horizontal_U0_img_out_data_stream_2_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal grad_horizontal_U0_img_out_data_stream_2_V_write : STD_LOGIC;
    signal add_with_color_U0_ap_start : STD_LOGIC;
    signal add_with_color_U0_ap_done : STD_LOGIC;
    signal add_with_color_U0_ap_continue : STD_LOGIC;
    signal add_with_color_U0_ap_idle : STD_LOGIC;
    signal add_with_color_U0_ap_ready : STD_LOGIC;
    signal add_with_color_U0_img_in0_data_stream_0_V_read : STD_LOGIC;
    signal add_with_color_U0_img_in0_data_stream_1_V_read : STD_LOGIC;
    signal add_with_color_U0_img_in0_data_stream_2_V_read : STD_LOGIC;
    signal add_with_color_U0_img_in1_data_stream_0_V_read : STD_LOGIC;
    signal add_with_color_U0_img_in1_data_stream_1_V_read : STD_LOGIC;
    signal add_with_color_U0_img_in1_data_stream_2_V_read : STD_LOGIC;
    signal add_with_color_U0_img_out_data_stream_0_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal add_with_color_U0_img_out_data_stream_0_V_write : STD_LOGIC;
    signal add_with_color_U0_img_out_data_stream_1_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal add_with_color_U0_img_out_data_stream_1_V_write : STD_LOGIC;
    signal add_with_color_U0_img_out_data_stream_2_V_din : STD_LOGIC_VECTOR (7 downto 0);
    signal add_with_color_U0_img_out_data_stream_2_V_write : STD_LOGIC;
    signal add_with_color_U0_start_out : STD_LOGIC;
    signal add_with_color_U0_start_write : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_start : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_done : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_continue : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_idle : STD_LOGIC;
    signal Mat2AXIvideo_U0_ap_ready : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_data_stream_0_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_data_stream_1_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_img_data_stream_2_V_read : STD_LOGIC;
    signal Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID : STD_LOGIC;
    signal Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP : STD_LOGIC_VECTOR (3 downto 0);
    signal Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST : STD_LOGIC_VECTOR (0 downto 0);
    signal Mat2AXIvideo_U0_OUTPUT_STREAM_TID : STD_LOGIC_VECTOR (0 downto 0);
    signal Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_sync_continue : STD_LOGIC;
    signal img_0_data_stream_0_full_n : STD_LOGIC;
    signal img_0_data_stream_0_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_0_data_stream_0_empty_n : STD_LOGIC;
    signal img_0_data_stream_1_full_n : STD_LOGIC;
    signal img_0_data_stream_1_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_0_data_stream_1_empty_n : STD_LOGIC;
    signal img_0_data_stream_2_full_n : STD_LOGIC;
    signal img_0_data_stream_2_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_0_data_stream_2_empty_n : STD_LOGIC;
    signal img_1a_data_stream_0_full_n : STD_LOGIC;
    signal img_1a_data_stream_0_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_1a_data_stream_0_empty_n : STD_LOGIC;
    signal img_1a_data_stream_1_full_n : STD_LOGIC;
    signal img_1a_data_stream_1_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_1a_data_stream_1_empty_n : STD_LOGIC;
    signal img_1a_data_stream_2_full_n : STD_LOGIC;
    signal img_1a_data_stream_2_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_1a_data_stream_2_empty_n : STD_LOGIC;
    signal img_1b_data_stream_0_full_n : STD_LOGIC;
    signal img_1b_data_stream_0_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_1b_data_stream_0_empty_n : STD_LOGIC;
    signal img_1b_data_stream_1_full_n : STD_LOGIC;
    signal img_1b_data_stream_1_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_1b_data_stream_1_empty_n : STD_LOGIC;
    signal img_1b_data_stream_2_full_n : STD_LOGIC;
    signal img_1b_data_stream_2_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_1b_data_stream_2_empty_n : STD_LOGIC;
    signal img_2a_data_stream_0_full_n : STD_LOGIC;
    signal img_2a_data_stream_0_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_2a_data_stream_0_empty_n : STD_LOGIC;
    signal img_2a_data_stream_1_full_n : STD_LOGIC;
    signal img_2a_data_stream_1_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_2a_data_stream_1_empty_n : STD_LOGIC;
    signal img_2a_data_stream_2_full_n : STD_LOGIC;
    signal img_2a_data_stream_2_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_2a_data_stream_2_empty_n : STD_LOGIC;
    signal img_2b_data_stream_0_full_n : STD_LOGIC;
    signal img_2b_data_stream_0_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_2b_data_stream_0_empty_n : STD_LOGIC;
    signal img_2b_data_stream_1_full_n : STD_LOGIC;
    signal img_2b_data_stream_1_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_2b_data_stream_1_empty_n : STD_LOGIC;
    signal img_2b_data_stream_2_full_n : STD_LOGIC;
    signal img_2b_data_stream_2_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_2b_data_stream_2_empty_n : STD_LOGIC;
    signal img_3_data_stream_0_full_n : STD_LOGIC;
    signal img_3_data_stream_0_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_3_data_stream_0_empty_n : STD_LOGIC;
    signal img_3_data_stream_1_full_n : STD_LOGIC;
    signal img_3_data_stream_1_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_3_data_stream_1_empty_n : STD_LOGIC;
    signal img_3_data_stream_2_full_n : STD_LOGIC;
    signal img_3_data_stream_2_dout : STD_LOGIC_VECTOR (7 downto 0);
    signal img_3_data_stream_2_empty_n : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal start_for_replicate_by2_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_replicate_by2_U0_full_n : STD_LOGIC;
    signal start_for_replicate_by2_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_replicate_by2_U0_empty_n : STD_LOGIC;
    signal start_for_grad_vertical_Mat_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_grad_vertical_Mat_U0_full_n : STD_LOGIC;
    signal start_for_grad_vertical_Mat_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_grad_vertical_Mat_U0_empty_n : STD_LOGIC;
    signal start_for_grad_horizontal_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_grad_horizontal_U0_full_n : STD_LOGIC;
    signal start_for_grad_horizontal_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_grad_horizontal_U0_empty_n : STD_LOGIC;
    signal start_for_add_with_color_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_add_with_color_U0_full_n : STD_LOGIC;
    signal start_for_add_with_color_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_add_with_color_U0_empty_n : STD_LOGIC;
    signal grad_horizontal_U0_start_full_n : STD_LOGIC;
    signal grad_horizontal_U0_start_write : STD_LOGIC;
    signal start_for_Mat2AXIvideo_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Mat2AXIvideo_U0_full_n : STD_LOGIC;
    signal start_for_Mat2AXIvideo_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_Mat2AXIvideo_U0_empty_n : STD_LOGIC;
    signal Mat2AXIvideo_U0_start_full_n : STD_LOGIC;
    signal Mat2AXIvideo_U0_start_write : STD_LOGIC;

    component AXIvideo2Mat IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        INPUT_STREAM_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        INPUT_STREAM_TVALID : IN STD_LOGIC;
        INPUT_STREAM_TREADY : OUT STD_LOGIC;
        INPUT_STREAM_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
        INPUT_STREAM_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        INPUT_STREAM_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        INPUT_STREAM_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
        INPUT_STREAM_TID : IN STD_LOGIC_VECTOR (0 downto 0);
        INPUT_STREAM_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
        img_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_0_V_full_n : IN STD_LOGIC;
        img_data_stream_0_V_write : OUT STD_LOGIC;
        img_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_1_V_full_n : IN STD_LOGIC;
        img_data_stream_1_V_write : OUT STD_LOGIC;
        img_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_2_V_full_n : IN STD_LOGIC;
        img_data_stream_2_V_write : OUT STD_LOGIC );
    end component;


    component replicate_by2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        img_in_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_in_data_stream_0_V_empty_n : IN STD_LOGIC;
        img_in_data_stream_0_V_read : OUT STD_LOGIC;
        img_in_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_in_data_stream_1_V_empty_n : IN STD_LOGIC;
        img_in_data_stream_1_V_read : OUT STD_LOGIC;
        img_in_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_in_data_stream_2_V_empty_n : IN STD_LOGIC;
        img_in_data_stream_2_V_read : OUT STD_LOGIC;
        img_out0_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_out0_data_stream_0_V_full_n : IN STD_LOGIC;
        img_out0_data_stream_0_V_write : OUT STD_LOGIC;
        img_out0_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_out0_data_stream_1_V_full_n : IN STD_LOGIC;
        img_out0_data_stream_1_V_write : OUT STD_LOGIC;
        img_out0_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_out0_data_stream_2_V_full_n : IN STD_LOGIC;
        img_out0_data_stream_2_V_write : OUT STD_LOGIC;
        img_out1_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_out1_data_stream_0_V_full_n : IN STD_LOGIC;
        img_out1_data_stream_0_V_write : OUT STD_LOGIC;
        img_out1_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_out1_data_stream_1_V_full_n : IN STD_LOGIC;
        img_out1_data_stream_1_V_write : OUT STD_LOGIC;
        img_out1_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_out1_data_stream_2_V_full_n : IN STD_LOGIC;
        img_out1_data_stream_2_V_write : OUT STD_LOGIC );
    end component;


    component grad_vertical_Mat_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        img_in_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_in_data_stream_0_V_empty_n : IN STD_LOGIC;
        img_in_data_stream_0_V_read : OUT STD_LOGIC;
        img_in_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_in_data_stream_1_V_empty_n : IN STD_LOGIC;
        img_in_data_stream_1_V_read : OUT STD_LOGIC;
        img_in_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_in_data_stream_2_V_empty_n : IN STD_LOGIC;
        img_in_data_stream_2_V_read : OUT STD_LOGIC;
        img_out_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_out_data_stream_0_V_full_n : IN STD_LOGIC;
        img_out_data_stream_0_V_write : OUT STD_LOGIC;
        img_out_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_out_data_stream_1_V_full_n : IN STD_LOGIC;
        img_out_data_stream_1_V_write : OUT STD_LOGIC;
        img_out_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_out_data_stream_2_V_full_n : IN STD_LOGIC;
        img_out_data_stream_2_V_write : OUT STD_LOGIC );
    end component;


    component grad_horizontal IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_in_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_in_data_stream_0_V_empty_n : IN STD_LOGIC;
        img_in_data_stream_0_V_read : OUT STD_LOGIC;
        img_in_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_in_data_stream_1_V_empty_n : IN STD_LOGIC;
        img_in_data_stream_1_V_read : OUT STD_LOGIC;
        img_in_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_in_data_stream_2_V_empty_n : IN STD_LOGIC;
        img_in_data_stream_2_V_read : OUT STD_LOGIC;
        img_out_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_out_data_stream_0_V_full_n : IN STD_LOGIC;
        img_out_data_stream_0_V_write : OUT STD_LOGIC;
        img_out_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_out_data_stream_1_V_full_n : IN STD_LOGIC;
        img_out_data_stream_1_V_write : OUT STD_LOGIC;
        img_out_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_out_data_stream_2_V_full_n : IN STD_LOGIC;
        img_out_data_stream_2_V_write : OUT STD_LOGIC );
    end component;


    component add_with_color IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_in0_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_in0_data_stream_0_V_empty_n : IN STD_LOGIC;
        img_in0_data_stream_0_V_read : OUT STD_LOGIC;
        img_in0_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_in0_data_stream_1_V_empty_n : IN STD_LOGIC;
        img_in0_data_stream_1_V_read : OUT STD_LOGIC;
        img_in0_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_in0_data_stream_2_V_empty_n : IN STD_LOGIC;
        img_in0_data_stream_2_V_read : OUT STD_LOGIC;
        img_in1_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_in1_data_stream_0_V_empty_n : IN STD_LOGIC;
        img_in1_data_stream_0_V_read : OUT STD_LOGIC;
        img_in1_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_in1_data_stream_1_V_empty_n : IN STD_LOGIC;
        img_in1_data_stream_1_V_read : OUT STD_LOGIC;
        img_in1_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_in1_data_stream_2_V_empty_n : IN STD_LOGIC;
        img_in1_data_stream_2_V_read : OUT STD_LOGIC;
        img_out_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_out_data_stream_0_V_full_n : IN STD_LOGIC;
        img_out_data_stream_0_V_write : OUT STD_LOGIC;
        img_out_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_out_data_stream_1_V_full_n : IN STD_LOGIC;
        img_out_data_stream_1_V_write : OUT STD_LOGIC;
        img_out_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
        img_out_data_stream_2_V_full_n : IN STD_LOGIC;
        img_out_data_stream_2_V_write : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC );
    end component;


    component Mat2AXIvideo IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        img_data_stream_0_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_0_V_empty_n : IN STD_LOGIC;
        img_data_stream_0_V_read : OUT STD_LOGIC;
        img_data_stream_1_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_1_V_empty_n : IN STD_LOGIC;
        img_data_stream_1_V_read : OUT STD_LOGIC;
        img_data_stream_2_V_dout : IN STD_LOGIC_VECTOR (7 downto 0);
        img_data_stream_2_V_empty_n : IN STD_LOGIC;
        img_data_stream_2_V_read : OUT STD_LOGIC;
        OUTPUT_STREAM_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        OUTPUT_STREAM_TVALID : OUT STD_LOGIC;
        OUTPUT_STREAM_TREADY : IN STD_LOGIC;
        OUTPUT_STREAM_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
        OUTPUT_STREAM_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        OUTPUT_STREAM_TUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        OUTPUT_STREAM_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
        OUTPUT_STREAM_TID : OUT STD_LOGIC_VECTOR (0 downto 0);
        OUTPUT_STREAM_TDEST : OUT STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component fifo_w8_d2_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (7 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (7 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_replicate_by2_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_grad_vertical_Mat_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_grad_horizontal_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_add_with_color_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component start_for_Mat2AXIvideo_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    AXIvideo2Mat_U0 : component AXIvideo2Mat
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => AXIvideo2Mat_U0_ap_start,
        start_full_n => start_for_replicate_by2_U0_full_n,
        ap_done => AXIvideo2Mat_U0_ap_done,
        ap_continue => AXIvideo2Mat_U0_ap_continue,
        ap_idle => AXIvideo2Mat_U0_ap_idle,
        ap_ready => AXIvideo2Mat_U0_ap_ready,
        start_out => AXIvideo2Mat_U0_start_out,
        start_write => AXIvideo2Mat_U0_start_write,
        INPUT_STREAM_TDATA => INPUT_STREAM_TDATA,
        INPUT_STREAM_TVALID => INPUT_STREAM_TVALID,
        INPUT_STREAM_TREADY => AXIvideo2Mat_U0_INPUT_STREAM_TREADY,
        INPUT_STREAM_TKEEP => INPUT_STREAM_TKEEP,
        INPUT_STREAM_TSTRB => INPUT_STREAM_TSTRB,
        INPUT_STREAM_TUSER => INPUT_STREAM_TUSER,
        INPUT_STREAM_TLAST => INPUT_STREAM_TLAST,
        INPUT_STREAM_TID => INPUT_STREAM_TID,
        INPUT_STREAM_TDEST => INPUT_STREAM_TDEST,
        img_data_stream_0_V_din => AXIvideo2Mat_U0_img_data_stream_0_V_din,
        img_data_stream_0_V_full_n => img_0_data_stream_0_full_n,
        img_data_stream_0_V_write => AXIvideo2Mat_U0_img_data_stream_0_V_write,
        img_data_stream_1_V_din => AXIvideo2Mat_U0_img_data_stream_1_V_din,
        img_data_stream_1_V_full_n => img_0_data_stream_1_full_n,
        img_data_stream_1_V_write => AXIvideo2Mat_U0_img_data_stream_1_V_write,
        img_data_stream_2_V_din => AXIvideo2Mat_U0_img_data_stream_2_V_din,
        img_data_stream_2_V_full_n => img_0_data_stream_2_full_n,
        img_data_stream_2_V_write => AXIvideo2Mat_U0_img_data_stream_2_V_write);

    replicate_by2_U0 : component replicate_by2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => replicate_by2_U0_ap_start,
        start_full_n => replicate_by2_U0_start_full_n,
        ap_done => replicate_by2_U0_ap_done,
        ap_continue => replicate_by2_U0_ap_continue,
        ap_idle => replicate_by2_U0_ap_idle,
        ap_ready => replicate_by2_U0_ap_ready,
        start_out => replicate_by2_U0_start_out,
        start_write => replicate_by2_U0_start_write,
        img_in_data_stream_0_V_dout => img_0_data_stream_0_dout,
        img_in_data_stream_0_V_empty_n => img_0_data_stream_0_empty_n,
        img_in_data_stream_0_V_read => replicate_by2_U0_img_in_data_stream_0_V_read,
        img_in_data_stream_1_V_dout => img_0_data_stream_1_dout,
        img_in_data_stream_1_V_empty_n => img_0_data_stream_1_empty_n,
        img_in_data_stream_1_V_read => replicate_by2_U0_img_in_data_stream_1_V_read,
        img_in_data_stream_2_V_dout => img_0_data_stream_2_dout,
        img_in_data_stream_2_V_empty_n => img_0_data_stream_2_empty_n,
        img_in_data_stream_2_V_read => replicate_by2_U0_img_in_data_stream_2_V_read,
        img_out0_data_stream_0_V_din => replicate_by2_U0_img_out0_data_stream_0_V_din,
        img_out0_data_stream_0_V_full_n => img_1a_data_stream_0_full_n,
        img_out0_data_stream_0_V_write => replicate_by2_U0_img_out0_data_stream_0_V_write,
        img_out0_data_stream_1_V_din => replicate_by2_U0_img_out0_data_stream_1_V_din,
        img_out0_data_stream_1_V_full_n => img_1a_data_stream_1_full_n,
        img_out0_data_stream_1_V_write => replicate_by2_U0_img_out0_data_stream_1_V_write,
        img_out0_data_stream_2_V_din => replicate_by2_U0_img_out0_data_stream_2_V_din,
        img_out0_data_stream_2_V_full_n => img_1a_data_stream_2_full_n,
        img_out0_data_stream_2_V_write => replicate_by2_U0_img_out0_data_stream_2_V_write,
        img_out1_data_stream_0_V_din => replicate_by2_U0_img_out1_data_stream_0_V_din,
        img_out1_data_stream_0_V_full_n => img_1b_data_stream_0_full_n,
        img_out1_data_stream_0_V_write => replicate_by2_U0_img_out1_data_stream_0_V_write,
        img_out1_data_stream_1_V_din => replicate_by2_U0_img_out1_data_stream_1_V_din,
        img_out1_data_stream_1_V_full_n => img_1b_data_stream_1_full_n,
        img_out1_data_stream_1_V_write => replicate_by2_U0_img_out1_data_stream_1_V_write,
        img_out1_data_stream_2_V_din => replicate_by2_U0_img_out1_data_stream_2_V_din,
        img_out1_data_stream_2_V_full_n => img_1b_data_stream_2_full_n,
        img_out1_data_stream_2_V_write => replicate_by2_U0_img_out1_data_stream_2_V_write);

    grad_vertical_Mat_U0 : component grad_vertical_Mat_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grad_vertical_Mat_U0_ap_start,
        start_full_n => start_for_add_with_color_U0_full_n,
        ap_done => grad_vertical_Mat_U0_ap_done,
        ap_continue => grad_vertical_Mat_U0_ap_continue,
        ap_idle => grad_vertical_Mat_U0_ap_idle,
        ap_ready => grad_vertical_Mat_U0_ap_ready,
        start_out => grad_vertical_Mat_U0_start_out,
        start_write => grad_vertical_Mat_U0_start_write,
        img_in_data_stream_0_V_dout => img_1a_data_stream_0_dout,
        img_in_data_stream_0_V_empty_n => img_1a_data_stream_0_empty_n,
        img_in_data_stream_0_V_read => grad_vertical_Mat_U0_img_in_data_stream_0_V_read,
        img_in_data_stream_1_V_dout => img_1a_data_stream_1_dout,
        img_in_data_stream_1_V_empty_n => img_1a_data_stream_1_empty_n,
        img_in_data_stream_1_V_read => grad_vertical_Mat_U0_img_in_data_stream_1_V_read,
        img_in_data_stream_2_V_dout => img_1a_data_stream_2_dout,
        img_in_data_stream_2_V_empty_n => img_1a_data_stream_2_empty_n,
        img_in_data_stream_2_V_read => grad_vertical_Mat_U0_img_in_data_stream_2_V_read,
        img_out_data_stream_0_V_din => grad_vertical_Mat_U0_img_out_data_stream_0_V_din,
        img_out_data_stream_0_V_full_n => img_2a_data_stream_0_full_n,
        img_out_data_stream_0_V_write => grad_vertical_Mat_U0_img_out_data_stream_0_V_write,
        img_out_data_stream_1_V_din => grad_vertical_Mat_U0_img_out_data_stream_1_V_din,
        img_out_data_stream_1_V_full_n => img_2a_data_stream_1_full_n,
        img_out_data_stream_1_V_write => grad_vertical_Mat_U0_img_out_data_stream_1_V_write,
        img_out_data_stream_2_V_din => grad_vertical_Mat_U0_img_out_data_stream_2_V_din,
        img_out_data_stream_2_V_full_n => img_2a_data_stream_2_full_n,
        img_out_data_stream_2_V_write => grad_vertical_Mat_U0_img_out_data_stream_2_V_write);

    grad_horizontal_U0 : component grad_horizontal
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grad_horizontal_U0_ap_start,
        ap_done => grad_horizontal_U0_ap_done,
        ap_continue => grad_horizontal_U0_ap_continue,
        ap_idle => grad_horizontal_U0_ap_idle,
        ap_ready => grad_horizontal_U0_ap_ready,
        img_in_data_stream_0_V_dout => img_1b_data_stream_0_dout,
        img_in_data_stream_0_V_empty_n => img_1b_data_stream_0_empty_n,
        img_in_data_stream_0_V_read => grad_horizontal_U0_img_in_data_stream_0_V_read,
        img_in_data_stream_1_V_dout => img_1b_data_stream_1_dout,
        img_in_data_stream_1_V_empty_n => img_1b_data_stream_1_empty_n,
        img_in_data_stream_1_V_read => grad_horizontal_U0_img_in_data_stream_1_V_read,
        img_in_data_stream_2_V_dout => img_1b_data_stream_2_dout,
        img_in_data_stream_2_V_empty_n => img_1b_data_stream_2_empty_n,
        img_in_data_stream_2_V_read => grad_horizontal_U0_img_in_data_stream_2_V_read,
        img_out_data_stream_0_V_din => grad_horizontal_U0_img_out_data_stream_0_V_din,
        img_out_data_stream_0_V_full_n => img_2b_data_stream_0_full_n,
        img_out_data_stream_0_V_write => grad_horizontal_U0_img_out_data_stream_0_V_write,
        img_out_data_stream_1_V_din => grad_horizontal_U0_img_out_data_stream_1_V_din,
        img_out_data_stream_1_V_full_n => img_2b_data_stream_1_full_n,
        img_out_data_stream_1_V_write => grad_horizontal_U0_img_out_data_stream_1_V_write,
        img_out_data_stream_2_V_din => grad_horizontal_U0_img_out_data_stream_2_V_din,
        img_out_data_stream_2_V_full_n => img_2b_data_stream_2_full_n,
        img_out_data_stream_2_V_write => grad_horizontal_U0_img_out_data_stream_2_V_write);

    add_with_color_U0 : component add_with_color
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => add_with_color_U0_ap_start,
        start_full_n => start_for_Mat2AXIvideo_U0_full_n,
        ap_done => add_with_color_U0_ap_done,
        ap_continue => add_with_color_U0_ap_continue,
        ap_idle => add_with_color_U0_ap_idle,
        ap_ready => add_with_color_U0_ap_ready,
        img_in0_data_stream_0_V_dout => img_2a_data_stream_0_dout,
        img_in0_data_stream_0_V_empty_n => img_2a_data_stream_0_empty_n,
        img_in0_data_stream_0_V_read => add_with_color_U0_img_in0_data_stream_0_V_read,
        img_in0_data_stream_1_V_dout => img_2a_data_stream_1_dout,
        img_in0_data_stream_1_V_empty_n => img_2a_data_stream_1_empty_n,
        img_in0_data_stream_1_V_read => add_with_color_U0_img_in0_data_stream_1_V_read,
        img_in0_data_stream_2_V_dout => img_2a_data_stream_2_dout,
        img_in0_data_stream_2_V_empty_n => img_2a_data_stream_2_empty_n,
        img_in0_data_stream_2_V_read => add_with_color_U0_img_in0_data_stream_2_V_read,
        img_in1_data_stream_0_V_dout => img_2b_data_stream_0_dout,
        img_in1_data_stream_0_V_empty_n => img_2b_data_stream_0_empty_n,
        img_in1_data_stream_0_V_read => add_with_color_U0_img_in1_data_stream_0_V_read,
        img_in1_data_stream_1_V_dout => img_2b_data_stream_1_dout,
        img_in1_data_stream_1_V_empty_n => img_2b_data_stream_1_empty_n,
        img_in1_data_stream_1_V_read => add_with_color_U0_img_in1_data_stream_1_V_read,
        img_in1_data_stream_2_V_dout => img_2b_data_stream_2_dout,
        img_in1_data_stream_2_V_empty_n => img_2b_data_stream_2_empty_n,
        img_in1_data_stream_2_V_read => add_with_color_U0_img_in1_data_stream_2_V_read,
        img_out_data_stream_0_V_din => add_with_color_U0_img_out_data_stream_0_V_din,
        img_out_data_stream_0_V_full_n => img_3_data_stream_0_full_n,
        img_out_data_stream_0_V_write => add_with_color_U0_img_out_data_stream_0_V_write,
        img_out_data_stream_1_V_din => add_with_color_U0_img_out_data_stream_1_V_din,
        img_out_data_stream_1_V_full_n => img_3_data_stream_1_full_n,
        img_out_data_stream_1_V_write => add_with_color_U0_img_out_data_stream_1_V_write,
        img_out_data_stream_2_V_din => add_with_color_U0_img_out_data_stream_2_V_din,
        img_out_data_stream_2_V_full_n => img_3_data_stream_2_full_n,
        img_out_data_stream_2_V_write => add_with_color_U0_img_out_data_stream_2_V_write,
        start_out => add_with_color_U0_start_out,
        start_write => add_with_color_U0_start_write);

    Mat2AXIvideo_U0 : component Mat2AXIvideo
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Mat2AXIvideo_U0_ap_start,
        ap_done => Mat2AXIvideo_U0_ap_done,
        ap_continue => Mat2AXIvideo_U0_ap_continue,
        ap_idle => Mat2AXIvideo_U0_ap_idle,
        ap_ready => Mat2AXIvideo_U0_ap_ready,
        img_data_stream_0_V_dout => img_3_data_stream_0_dout,
        img_data_stream_0_V_empty_n => img_3_data_stream_0_empty_n,
        img_data_stream_0_V_read => Mat2AXIvideo_U0_img_data_stream_0_V_read,
        img_data_stream_1_V_dout => img_3_data_stream_1_dout,
        img_data_stream_1_V_empty_n => img_3_data_stream_1_empty_n,
        img_data_stream_1_V_read => Mat2AXIvideo_U0_img_data_stream_1_V_read,
        img_data_stream_2_V_dout => img_3_data_stream_2_dout,
        img_data_stream_2_V_empty_n => img_3_data_stream_2_empty_n,
        img_data_stream_2_V_read => Mat2AXIvideo_U0_img_data_stream_2_V_read,
        OUTPUT_STREAM_TDATA => Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA,
        OUTPUT_STREAM_TVALID => Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID,
        OUTPUT_STREAM_TREADY => OUTPUT_STREAM_TREADY,
        OUTPUT_STREAM_TKEEP => Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP,
        OUTPUT_STREAM_TSTRB => Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB,
        OUTPUT_STREAM_TUSER => Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER,
        OUTPUT_STREAM_TLAST => Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST,
        OUTPUT_STREAM_TID => Mat2AXIvideo_U0_OUTPUT_STREAM_TID,
        OUTPUT_STREAM_TDEST => Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST);

    img_0_data_stream_0_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2Mat_U0_img_data_stream_0_V_din,
        if_full_n => img_0_data_stream_0_full_n,
        if_write => AXIvideo2Mat_U0_img_data_stream_0_V_write,
        if_dout => img_0_data_stream_0_dout,
        if_empty_n => img_0_data_stream_0_empty_n,
        if_read => replicate_by2_U0_img_in_data_stream_0_V_read);

    img_0_data_stream_1_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2Mat_U0_img_data_stream_1_V_din,
        if_full_n => img_0_data_stream_1_full_n,
        if_write => AXIvideo2Mat_U0_img_data_stream_1_V_write,
        if_dout => img_0_data_stream_1_dout,
        if_empty_n => img_0_data_stream_1_empty_n,
        if_read => replicate_by2_U0_img_in_data_stream_1_V_read);

    img_0_data_stream_2_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => AXIvideo2Mat_U0_img_data_stream_2_V_din,
        if_full_n => img_0_data_stream_2_full_n,
        if_write => AXIvideo2Mat_U0_img_data_stream_2_V_write,
        if_dout => img_0_data_stream_2_dout,
        if_empty_n => img_0_data_stream_2_empty_n,
        if_read => replicate_by2_U0_img_in_data_stream_2_V_read);

    img_1a_data_stream_0_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => replicate_by2_U0_img_out0_data_stream_0_V_din,
        if_full_n => img_1a_data_stream_0_full_n,
        if_write => replicate_by2_U0_img_out0_data_stream_0_V_write,
        if_dout => img_1a_data_stream_0_dout,
        if_empty_n => img_1a_data_stream_0_empty_n,
        if_read => grad_vertical_Mat_U0_img_in_data_stream_0_V_read);

    img_1a_data_stream_1_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => replicate_by2_U0_img_out0_data_stream_1_V_din,
        if_full_n => img_1a_data_stream_1_full_n,
        if_write => replicate_by2_U0_img_out0_data_stream_1_V_write,
        if_dout => img_1a_data_stream_1_dout,
        if_empty_n => img_1a_data_stream_1_empty_n,
        if_read => grad_vertical_Mat_U0_img_in_data_stream_1_V_read);

    img_1a_data_stream_2_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => replicate_by2_U0_img_out0_data_stream_2_V_din,
        if_full_n => img_1a_data_stream_2_full_n,
        if_write => replicate_by2_U0_img_out0_data_stream_2_V_write,
        if_dout => img_1a_data_stream_2_dout,
        if_empty_n => img_1a_data_stream_2_empty_n,
        if_read => grad_vertical_Mat_U0_img_in_data_stream_2_V_read);

    img_1b_data_stream_0_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => replicate_by2_U0_img_out1_data_stream_0_V_din,
        if_full_n => img_1b_data_stream_0_full_n,
        if_write => replicate_by2_U0_img_out1_data_stream_0_V_write,
        if_dout => img_1b_data_stream_0_dout,
        if_empty_n => img_1b_data_stream_0_empty_n,
        if_read => grad_horizontal_U0_img_in_data_stream_0_V_read);

    img_1b_data_stream_1_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => replicate_by2_U0_img_out1_data_stream_1_V_din,
        if_full_n => img_1b_data_stream_1_full_n,
        if_write => replicate_by2_U0_img_out1_data_stream_1_V_write,
        if_dout => img_1b_data_stream_1_dout,
        if_empty_n => img_1b_data_stream_1_empty_n,
        if_read => grad_horizontal_U0_img_in_data_stream_1_V_read);

    img_1b_data_stream_2_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => replicate_by2_U0_img_out1_data_stream_2_V_din,
        if_full_n => img_1b_data_stream_2_full_n,
        if_write => replicate_by2_U0_img_out1_data_stream_2_V_write,
        if_dout => img_1b_data_stream_2_dout,
        if_empty_n => img_1b_data_stream_2_empty_n,
        if_read => grad_horizontal_U0_img_in_data_stream_2_V_read);

    img_2a_data_stream_0_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grad_vertical_Mat_U0_img_out_data_stream_0_V_din,
        if_full_n => img_2a_data_stream_0_full_n,
        if_write => grad_vertical_Mat_U0_img_out_data_stream_0_V_write,
        if_dout => img_2a_data_stream_0_dout,
        if_empty_n => img_2a_data_stream_0_empty_n,
        if_read => add_with_color_U0_img_in0_data_stream_0_V_read);

    img_2a_data_stream_1_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grad_vertical_Mat_U0_img_out_data_stream_1_V_din,
        if_full_n => img_2a_data_stream_1_full_n,
        if_write => grad_vertical_Mat_U0_img_out_data_stream_1_V_write,
        if_dout => img_2a_data_stream_1_dout,
        if_empty_n => img_2a_data_stream_1_empty_n,
        if_read => add_with_color_U0_img_in0_data_stream_1_V_read);

    img_2a_data_stream_2_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grad_vertical_Mat_U0_img_out_data_stream_2_V_din,
        if_full_n => img_2a_data_stream_2_full_n,
        if_write => grad_vertical_Mat_U0_img_out_data_stream_2_V_write,
        if_dout => img_2a_data_stream_2_dout,
        if_empty_n => img_2a_data_stream_2_empty_n,
        if_read => add_with_color_U0_img_in0_data_stream_2_V_read);

    img_2b_data_stream_0_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grad_horizontal_U0_img_out_data_stream_0_V_din,
        if_full_n => img_2b_data_stream_0_full_n,
        if_write => grad_horizontal_U0_img_out_data_stream_0_V_write,
        if_dout => img_2b_data_stream_0_dout,
        if_empty_n => img_2b_data_stream_0_empty_n,
        if_read => add_with_color_U0_img_in1_data_stream_0_V_read);

    img_2b_data_stream_1_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grad_horizontal_U0_img_out_data_stream_1_V_din,
        if_full_n => img_2b_data_stream_1_full_n,
        if_write => grad_horizontal_U0_img_out_data_stream_1_V_write,
        if_dout => img_2b_data_stream_1_dout,
        if_empty_n => img_2b_data_stream_1_empty_n,
        if_read => add_with_color_U0_img_in1_data_stream_1_V_read);

    img_2b_data_stream_2_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grad_horizontal_U0_img_out_data_stream_2_V_din,
        if_full_n => img_2b_data_stream_2_full_n,
        if_write => grad_horizontal_U0_img_out_data_stream_2_V_write,
        if_dout => img_2b_data_stream_2_dout,
        if_empty_n => img_2b_data_stream_2_empty_n,
        if_read => add_with_color_U0_img_in1_data_stream_2_V_read);

    img_3_data_stream_0_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => add_with_color_U0_img_out_data_stream_0_V_din,
        if_full_n => img_3_data_stream_0_full_n,
        if_write => add_with_color_U0_img_out_data_stream_0_V_write,
        if_dout => img_3_data_stream_0_dout,
        if_empty_n => img_3_data_stream_0_empty_n,
        if_read => Mat2AXIvideo_U0_img_data_stream_0_V_read);

    img_3_data_stream_1_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => add_with_color_U0_img_out_data_stream_1_V_din,
        if_full_n => img_3_data_stream_1_full_n,
        if_write => add_with_color_U0_img_out_data_stream_1_V_write,
        if_dout => img_3_data_stream_1_dout,
        if_empty_n => img_3_data_stream_1_empty_n,
        if_read => Mat2AXIvideo_U0_img_data_stream_1_V_read);

    img_3_data_stream_2_U : component fifo_w8_d2_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => add_with_color_U0_img_out_data_stream_2_V_din,
        if_full_n => img_3_data_stream_2_full_n,
        if_write => add_with_color_U0_img_out_data_stream_2_V_write,
        if_dout => img_3_data_stream_2_dout,
        if_empty_n => img_3_data_stream_2_empty_n,
        if_read => Mat2AXIvideo_U0_img_data_stream_2_V_read);

    start_for_replicate_by2_U0_U : component start_for_replicate_by2_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_replicate_by2_U0_din,
        if_full_n => start_for_replicate_by2_U0_full_n,
        if_write => AXIvideo2Mat_U0_start_write,
        if_dout => start_for_replicate_by2_U0_dout,
        if_empty_n => start_for_replicate_by2_U0_empty_n,
        if_read => replicate_by2_U0_ap_ready);

    start_for_grad_vertical_Mat_U0_U : component start_for_grad_vertical_Mat_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_grad_vertical_Mat_U0_din,
        if_full_n => start_for_grad_vertical_Mat_U0_full_n,
        if_write => replicate_by2_U0_start_write,
        if_dout => start_for_grad_vertical_Mat_U0_dout,
        if_empty_n => start_for_grad_vertical_Mat_U0_empty_n,
        if_read => grad_vertical_Mat_U0_ap_ready);

    start_for_grad_horizontal_U0_U : component start_for_grad_horizontal_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_grad_horizontal_U0_din,
        if_full_n => start_for_grad_horizontal_U0_full_n,
        if_write => replicate_by2_U0_start_write,
        if_dout => start_for_grad_horizontal_U0_dout,
        if_empty_n => start_for_grad_horizontal_U0_empty_n,
        if_read => grad_horizontal_U0_ap_ready);

    start_for_add_with_color_U0_U : component start_for_add_with_color_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_add_with_color_U0_din,
        if_full_n => start_for_add_with_color_U0_full_n,
        if_write => grad_vertical_Mat_U0_start_write,
        if_dout => start_for_add_with_color_U0_dout,
        if_empty_n => start_for_add_with_color_U0_empty_n,
        if_read => add_with_color_U0_ap_ready);

    start_for_Mat2AXIvideo_U0_U : component start_for_Mat2AXIvideo_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_Mat2AXIvideo_U0_din,
        if_full_n => start_for_Mat2AXIvideo_U0_full_n,
        if_write => add_with_color_U0_start_write,
        if_dout => start_for_Mat2AXIvideo_U0_dout,
        if_empty_n => start_for_Mat2AXIvideo_U0_empty_n,
        if_read => Mat2AXIvideo_U0_ap_ready);




    AXIvideo2Mat_U0_ap_continue <= ap_const_logic_1;
    AXIvideo2Mat_U0_ap_start <= ap_start;
    INPUT_STREAM_TREADY <= AXIvideo2Mat_U0_INPUT_STREAM_TREADY;
    Mat2AXIvideo_U0_ap_continue <= ap_const_logic_1;
    Mat2AXIvideo_U0_ap_start <= start_for_Mat2AXIvideo_U0_empty_n;
    Mat2AXIvideo_U0_start_full_n <= ap_const_logic_1;
    Mat2AXIvideo_U0_start_write <= ap_const_logic_0;
    OUTPUT_STREAM_TDATA <= Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA;
    OUTPUT_STREAM_TDEST <= Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST;
    OUTPUT_STREAM_TID <= Mat2AXIvideo_U0_OUTPUT_STREAM_TID;
    OUTPUT_STREAM_TKEEP <= Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP;
    OUTPUT_STREAM_TLAST <= Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST;
    OUTPUT_STREAM_TSTRB <= Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB;
    OUTPUT_STREAM_TUSER <= Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER;
    OUTPUT_STREAM_TVALID <= Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID;
    add_with_color_U0_ap_continue <= ap_const_logic_1;
    add_with_color_U0_ap_start <= start_for_add_with_color_U0_empty_n;
    ap_done <= Mat2AXIvideo_U0_ap_done;
    ap_idle <= (replicate_by2_U0_ap_idle and grad_vertical_Mat_U0_ap_idle and grad_horizontal_U0_ap_idle and add_with_color_U0_ap_idle and Mat2AXIvideo_U0_ap_idle and AXIvideo2Mat_U0_ap_idle);
    ap_ready <= AXIvideo2Mat_U0_ap_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_continue <= ap_const_logic_1;
    ap_sync_done <= Mat2AXIvideo_U0_ap_done;
    ap_sync_ready <= AXIvideo2Mat_U0_ap_ready;
    grad_horizontal_U0_ap_continue <= ap_const_logic_1;
    grad_horizontal_U0_ap_start <= start_for_grad_horizontal_U0_empty_n;
    grad_horizontal_U0_start_full_n <= ap_const_logic_1;
    grad_horizontal_U0_start_write <= ap_const_logic_0;
    grad_vertical_Mat_U0_ap_continue <= ap_const_logic_1;
    grad_vertical_Mat_U0_ap_start <= start_for_grad_vertical_Mat_U0_empty_n;
    replicate_by2_U0_ap_continue <= ap_const_logic_1;
    replicate_by2_U0_ap_start <= start_for_replicate_by2_U0_empty_n;
    replicate_by2_U0_start_full_n <= (start_for_grad_vertical_Mat_U0_full_n and start_for_grad_horizontal_U0_full_n);
    start_for_Mat2AXIvideo_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_add_with_color_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_grad_horizontal_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_grad_vertical_Mat_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_replicate_by2_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
