// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "replicate_by2.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic replicate_by2::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic replicate_by2::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> replicate_by2::ap_ST_fsm_state1 = "1";
const sc_lv<2> replicate_by2::ap_ST_fsm_state2 = "10";
const sc_lv<32> replicate_by2::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> replicate_by2::ap_const_lv32_1 = "1";
const sc_lv<16> replicate_by2::ap_const_lv16_0 = "0000000000000000";
const sc_lv<1> replicate_by2::ap_const_lv1_0 = "0";
const sc_lv<1> replicate_by2::ap_const_lv1_1 = "1";
const sc_lv<16> replicate_by2::ap_const_lv16_1 = "1";
const sc_lv<16> replicate_by2::ap_const_lv16_BD0F = "1011110100001111";
const bool replicate_by2::ap_const_boolean_1 = true;

replicate_by2::replicate_by2(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( img_out1_data_stream_2_V_full_n );

    SC_METHOD(thread_ap_done);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( img_out1_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_flatten_fu_260_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_exitcond_flatten_fu_260_p2);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( img_out1_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( indvar_flatten2_reg_240 );

    SC_METHOD(thread_img_in_data_stream_0_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_in_data_stream_0_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( img_out1_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_in_data_stream_1_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_in_data_stream_1_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( img_out1_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_in_data_stream_2_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_in_data_stream_2_V_read);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( img_out1_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_out0_data_stream_0_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_out0_data_stream_0_V_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_0_V_dout );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( img_out1_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_out0_data_stream_0_V_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( img_out1_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_out0_data_stream_1_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_out0_data_stream_1_V_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( img_in_data_stream_1_V_dout );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( img_out1_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_out0_data_stream_1_V_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( img_out1_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_out0_data_stream_2_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_out0_data_stream_2_V_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( img_in_data_stream_2_V_dout );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( img_out1_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_out0_data_stream_2_V_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( img_out1_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_out1_data_stream_0_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_out1_data_stream_0_V_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_0_V_dout );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( img_out1_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_out1_data_stream_0_V_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( img_out1_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_out1_data_stream_1_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_out1_data_stream_1_V_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( img_in_data_stream_1_V_dout );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( img_out1_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_out1_data_stream_1_V_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( img_out1_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_out1_data_stream_2_V_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_out1_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_out1_data_stream_2_V_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( img_in_data_stream_2_V_dout );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( img_out1_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_img_out1_data_stream_2_V_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( img_out1_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_indvar_flatten_next_fu_254_p2);
    sensitive << ( indvar_flatten2_reg_240 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( img_out1_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_flatten_fu_260_p2 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( img_in_data_stream_0_V_empty_n );
    sensitive << ( img_in_data_stream_1_V_empty_n );
    sensitive << ( img_in_data_stream_2_V_empty_n );
    sensitive << ( img_out0_data_stream_0_V_full_n );
    sensitive << ( img_out0_data_stream_1_V_full_n );
    sensitive << ( img_out0_data_stream_2_V_full_n );
    sensitive << ( img_out1_data_stream_0_V_full_n );
    sensitive << ( img_out1_data_stream_1_V_full_n );
    sensitive << ( img_out1_data_stream_2_V_full_n );
    sensitive << ( ap_CS_fsm_state2 );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "01";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "replicate_by2_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, img_in_data_stream_0_V_dout, "(port)img_in_data_stream_0_V_dout");
    sc_trace(mVcdFile, img_in_data_stream_0_V_empty_n, "(port)img_in_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, img_in_data_stream_0_V_read, "(port)img_in_data_stream_0_V_read");
    sc_trace(mVcdFile, img_in_data_stream_1_V_dout, "(port)img_in_data_stream_1_V_dout");
    sc_trace(mVcdFile, img_in_data_stream_1_V_empty_n, "(port)img_in_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, img_in_data_stream_1_V_read, "(port)img_in_data_stream_1_V_read");
    sc_trace(mVcdFile, img_in_data_stream_2_V_dout, "(port)img_in_data_stream_2_V_dout");
    sc_trace(mVcdFile, img_in_data_stream_2_V_empty_n, "(port)img_in_data_stream_2_V_empty_n");
    sc_trace(mVcdFile, img_in_data_stream_2_V_read, "(port)img_in_data_stream_2_V_read");
    sc_trace(mVcdFile, img_out0_data_stream_0_V_din, "(port)img_out0_data_stream_0_V_din");
    sc_trace(mVcdFile, img_out0_data_stream_0_V_full_n, "(port)img_out0_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_out0_data_stream_0_V_write, "(port)img_out0_data_stream_0_V_write");
    sc_trace(mVcdFile, img_out0_data_stream_1_V_din, "(port)img_out0_data_stream_1_V_din");
    sc_trace(mVcdFile, img_out0_data_stream_1_V_full_n, "(port)img_out0_data_stream_1_V_full_n");
    sc_trace(mVcdFile, img_out0_data_stream_1_V_write, "(port)img_out0_data_stream_1_V_write");
    sc_trace(mVcdFile, img_out0_data_stream_2_V_din, "(port)img_out0_data_stream_2_V_din");
    sc_trace(mVcdFile, img_out0_data_stream_2_V_full_n, "(port)img_out0_data_stream_2_V_full_n");
    sc_trace(mVcdFile, img_out0_data_stream_2_V_write, "(port)img_out0_data_stream_2_V_write");
    sc_trace(mVcdFile, img_out1_data_stream_0_V_din, "(port)img_out1_data_stream_0_V_din");
    sc_trace(mVcdFile, img_out1_data_stream_0_V_full_n, "(port)img_out1_data_stream_0_V_full_n");
    sc_trace(mVcdFile, img_out1_data_stream_0_V_write, "(port)img_out1_data_stream_0_V_write");
    sc_trace(mVcdFile, img_out1_data_stream_1_V_din, "(port)img_out1_data_stream_1_V_din");
    sc_trace(mVcdFile, img_out1_data_stream_1_V_full_n, "(port)img_out1_data_stream_1_V_full_n");
    sc_trace(mVcdFile, img_out1_data_stream_1_V_write, "(port)img_out1_data_stream_1_V_write");
    sc_trace(mVcdFile, img_out1_data_stream_2_V_din, "(port)img_out1_data_stream_2_V_din");
    sc_trace(mVcdFile, img_out1_data_stream_2_V_full_n, "(port)img_out1_data_stream_2_V_full_n");
    sc_trace(mVcdFile, img_out1_data_stream_2_V_write, "(port)img_out1_data_stream_2_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, img_in_data_stream_0_V_blk_n, "img_in_data_stream_0_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, img_in_data_stream_1_V_blk_n, "img_in_data_stream_1_V_blk_n");
    sc_trace(mVcdFile, img_in_data_stream_2_V_blk_n, "img_in_data_stream_2_V_blk_n");
    sc_trace(mVcdFile, img_out0_data_stream_0_V_blk_n, "img_out0_data_stream_0_V_blk_n");
    sc_trace(mVcdFile, img_out0_data_stream_1_V_blk_n, "img_out0_data_stream_1_V_blk_n");
    sc_trace(mVcdFile, img_out0_data_stream_2_V_blk_n, "img_out0_data_stream_2_V_blk_n");
    sc_trace(mVcdFile, img_out1_data_stream_0_V_blk_n, "img_out1_data_stream_0_V_blk_n");
    sc_trace(mVcdFile, img_out1_data_stream_1_V_blk_n, "img_out1_data_stream_1_V_blk_n");
    sc_trace(mVcdFile, img_out1_data_stream_2_V_blk_n, "img_out1_data_stream_2_V_blk_n");
    sc_trace(mVcdFile, indvar_flatten_next_fu_254_p2, "indvar_flatten_next_fu_254_p2");
    sc_trace(mVcdFile, ap_block_state2, "ap_block_state2");
    sc_trace(mVcdFile, indvar_flatten2_reg_240, "indvar_flatten2_reg_240");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, exitcond_flatten_fu_260_p2, "exitcond_flatten_fu_260_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

replicate_by2::~replicate_by2() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void replicate_by2::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_0_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_1_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_2_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_2_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_2_V_full_n.read())) && 
                    esl_seteq<1,1,1>(exitcond_flatten_fu_260_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_0_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_1_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_2_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_2_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_2_V_full_n.read())) && 
         esl_seteq<1,1,1>(exitcond_flatten_fu_260_p2.read(), ap_const_lv1_0))) {
        indvar_flatten2_reg_240 = indvar_flatten_next_fu_254_p2.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                 !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                 !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_0_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_1_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_2_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_2_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_2_V_full_n.read())) && 
                 esl_seteq<1,1,1>(exitcond_flatten_fu_260_p2.read(), ap_const_lv1_1)))) {
        indvar_flatten2_reg_240 = ap_const_lv16_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
}

void replicate_by2::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void replicate_by2::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void replicate_by2::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void replicate_by2::thread_ap_block_state2() {
    ap_block_state2 = (esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_0_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_1_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_2_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_2_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_2_V_full_n.read()));
}

void replicate_by2::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_0_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_1_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_2_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_2_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_2_V_full_n.read())) && 
         esl_seteq<1,1,1>(exitcond_flatten_fu_260_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void replicate_by2::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void replicate_by2::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void replicate_by2::thread_exitcond_flatten_fu_260_p2() {
    exitcond_flatten_fu_260_p2 = (!indvar_flatten2_reg_240.read().is_01() || !ap_const_lv16_BD0F.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten2_reg_240.read() == ap_const_lv16_BD0F);
}

void replicate_by2::thread_img_in_data_stream_0_V_blk_n() {
    if ((!(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        img_in_data_stream_0_V_blk_n = img_in_data_stream_0_V_empty_n.read();
    } else {
        img_in_data_stream_0_V_blk_n = ap_const_logic_1;
    }
}

void replicate_by2::thread_img_in_data_stream_0_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_0_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_1_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_2_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_2_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_2_V_full_n.read())))) {
        img_in_data_stream_0_V_read = ap_const_logic_1;
    } else {
        img_in_data_stream_0_V_read = ap_const_logic_0;
    }
}

void replicate_by2::thread_img_in_data_stream_1_V_blk_n() {
    if ((!(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        img_in_data_stream_1_V_blk_n = img_in_data_stream_1_V_empty_n.read();
    } else {
        img_in_data_stream_1_V_blk_n = ap_const_logic_1;
    }
}

void replicate_by2::thread_img_in_data_stream_1_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_0_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_1_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_2_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_2_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_2_V_full_n.read())))) {
        img_in_data_stream_1_V_read = ap_const_logic_1;
    } else {
        img_in_data_stream_1_V_read = ap_const_logic_0;
    }
}

void replicate_by2::thread_img_in_data_stream_2_V_blk_n() {
    if ((!(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        img_in_data_stream_2_V_blk_n = img_in_data_stream_2_V_empty_n.read();
    } else {
        img_in_data_stream_2_V_blk_n = ap_const_logic_1;
    }
}

void replicate_by2::thread_img_in_data_stream_2_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_0_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_1_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_2_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_2_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_2_V_full_n.read())))) {
        img_in_data_stream_2_V_read = ap_const_logic_1;
    } else {
        img_in_data_stream_2_V_read = ap_const_logic_0;
    }
}

void replicate_by2::thread_img_out0_data_stream_0_V_blk_n() {
    if ((!(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        img_out0_data_stream_0_V_blk_n = img_out0_data_stream_0_V_full_n.read();
    } else {
        img_out0_data_stream_0_V_blk_n = ap_const_logic_1;
    }
}

void replicate_by2::thread_img_out0_data_stream_0_V_din() {
    img_out0_data_stream_0_V_din = img_in_data_stream_0_V_dout.read();
}

void replicate_by2::thread_img_out0_data_stream_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_0_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_1_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_2_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_2_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_2_V_full_n.read())))) {
        img_out0_data_stream_0_V_write = ap_const_logic_1;
    } else {
        img_out0_data_stream_0_V_write = ap_const_logic_0;
    }
}

void replicate_by2::thread_img_out0_data_stream_1_V_blk_n() {
    if ((!(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        img_out0_data_stream_1_V_blk_n = img_out0_data_stream_1_V_full_n.read();
    } else {
        img_out0_data_stream_1_V_blk_n = ap_const_logic_1;
    }
}

void replicate_by2::thread_img_out0_data_stream_1_V_din() {
    img_out0_data_stream_1_V_din = img_in_data_stream_1_V_dout.read();
}

void replicate_by2::thread_img_out0_data_stream_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_0_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_1_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_2_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_2_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_2_V_full_n.read())))) {
        img_out0_data_stream_1_V_write = ap_const_logic_1;
    } else {
        img_out0_data_stream_1_V_write = ap_const_logic_0;
    }
}

void replicate_by2::thread_img_out0_data_stream_2_V_blk_n() {
    if ((!(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        img_out0_data_stream_2_V_blk_n = img_out0_data_stream_2_V_full_n.read();
    } else {
        img_out0_data_stream_2_V_blk_n = ap_const_logic_1;
    }
}

void replicate_by2::thread_img_out0_data_stream_2_V_din() {
    img_out0_data_stream_2_V_din = img_in_data_stream_2_V_dout.read();
}

void replicate_by2::thread_img_out0_data_stream_2_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_0_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_1_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_2_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_2_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_2_V_full_n.read())))) {
        img_out0_data_stream_2_V_write = ap_const_logic_1;
    } else {
        img_out0_data_stream_2_V_write = ap_const_logic_0;
    }
}

void replicate_by2::thread_img_out1_data_stream_0_V_blk_n() {
    if ((!(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        img_out1_data_stream_0_V_blk_n = img_out1_data_stream_0_V_full_n.read();
    } else {
        img_out1_data_stream_0_V_blk_n = ap_const_logic_1;
    }
}

void replicate_by2::thread_img_out1_data_stream_0_V_din() {
    img_out1_data_stream_0_V_din = img_in_data_stream_0_V_dout.read();
}

void replicate_by2::thread_img_out1_data_stream_0_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_0_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_1_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_2_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_2_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_2_V_full_n.read())))) {
        img_out1_data_stream_0_V_write = ap_const_logic_1;
    } else {
        img_out1_data_stream_0_V_write = ap_const_logic_0;
    }
}

void replicate_by2::thread_img_out1_data_stream_1_V_blk_n() {
    if ((!(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        img_out1_data_stream_1_V_blk_n = img_out1_data_stream_1_V_full_n.read();
    } else {
        img_out1_data_stream_1_V_blk_n = ap_const_logic_1;
    }
}

void replicate_by2::thread_img_out1_data_stream_1_V_din() {
    img_out1_data_stream_1_V_din = img_in_data_stream_1_V_dout.read();
}

void replicate_by2::thread_img_out1_data_stream_1_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_0_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_1_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_2_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_2_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_2_V_full_n.read())))) {
        img_out1_data_stream_1_V_write = ap_const_logic_1;
    } else {
        img_out1_data_stream_1_V_write = ap_const_logic_0;
    }
}

void replicate_by2::thread_img_out1_data_stream_2_V_blk_n() {
    if ((!(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        img_out1_data_stream_2_V_blk_n = img_out1_data_stream_2_V_full_n.read();
    } else {
        img_out1_data_stream_2_V_blk_n = ap_const_logic_1;
    }
}

void replicate_by2::thread_img_out1_data_stream_2_V_din() {
    img_out1_data_stream_2_V_din = img_in_data_stream_2_V_dout.read();
}

void replicate_by2::thread_img_out1_data_stream_2_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_0_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_1_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_2_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_2_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_2_V_full_n.read())))) {
        img_out1_data_stream_2_V_write = ap_const_logic_1;
    } else {
        img_out1_data_stream_2_V_write = ap_const_logic_0;
    }
}

void replicate_by2::thread_indvar_flatten_next_fu_254_p2() {
    indvar_flatten_next_fu_254_p2 = (!indvar_flatten2_reg_240.read().is_01() || !ap_const_lv16_1.is_01())? sc_lv<16>(): (sc_biguint<16>(indvar_flatten2_reg_240.read()) + sc_biguint<16>(ap_const_lv16_1));
}

void replicate_by2::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_0_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_1_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_in_data_stream_2_V_empty_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out0_data_stream_2_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_0_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_1_V_full_n.read()) || esl_seteq<1,1,1>(ap_const_logic_0, img_out1_data_stream_2_V_full_n.read())) && 
         esl_seteq<1,1,1>(exitcond_flatten_fu_260_p2.read(), ap_const_lv1_1))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void replicate_by2::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void replicate_by2::thread_start_out() {
    start_out = real_start.read();
}

void replicate_by2::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void replicate_by2::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, real_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state2;
break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

